name: Hola mundo

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: Saludar
        run: echo 'Hola Mundo'

      - name: Informacion Basica
        run: |
          echo "REF: $GITHUB_REF"
          echo "JOB: $GITHUB_JOB"
          echo "ACTION: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"
          echo "Event: $GITHUB_EVENT_NAME"

  archivo:
    runs-on: ubuntu-latest
    needs: [hola]

    steps:
      - name: Touch file
        run: touch hola.txt
      
      - name: Set text
        run: echo "Leit euer Ohr einer Legende....RAMMSTEIN!" >> hola.txt

      - name: Read file
        run: cat hola.txt

      - name: Basic Info
        run: |
          echo "REF: $GITHUB_REF"
          echo "JOB: $GITHUB_JOB"
          echo "ACTION: $GITHUB_ACTION"
          echo "ACTOR: $GITHUB_ACTOR"
          echo "EVENT: $GITHUB_EVENT_NAME"

  otro:
    runs-on: ubuntu-latest
    needs: [archivo]

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.7

      - name: LS 
        run: ls -al 