name: Test Composite Action 

on:
  push:
    branches:
      - main

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ls
        users: ./.github/actions/my-action