name: Test Commands

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: ls 
        run: |
          chmod +x script.sh
          ./script.sh