name: Test Commands

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0

      - name: Check Node Version
        run: node --version
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.33.0

      - name: Check PHP version
        run: php --version